apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo
  labels:
    app: catalogo 
    pdb: 'true'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalogo
  template:
    metadata:
      labels:
        app: catalogo
    spec:
      containers: 
        - name: catalogo
          image: adenilsonkon/devopslabs-catalogo:latest
          ports:
            - containerPort: 3333
          envFrom:
            - secretRef:
                name: catalogo-secret
            - configMapRef:
                name: db-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogo
  labels:
    istio-metrics: 'true'
spec:
  selector:
    app: catalogo
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      name: http
    - protocol: TCP
      port: 15020
      targetPort: 15020
      name: http-metrics
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    pdb: 'zero'
spec:
  selector:
    matchLabels:
      app: psql-db
  serviceName: psql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: psql-db
    spec:
      containers:
      - name: psql-db
        image: postgres:13.2
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: db-secret
          - configMapRef:
              name: db-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data/db
            subPath: db
      volumes:
        - name: db-data
          emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    istio-metrics: 'true'
spec:
  selector:
    app: psql-db
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
  type: ClusterIP
--- 

