apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: api-prd
  labels:
    istio-metrics: "true"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 15020
      name: http-metrics
  type: ClusterIP